apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30660

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.7
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "rootpw"
            - name: MARIADB_DATABASE
              value: "vdiusers"
            - name: MARIADB_USER
              value: "vdiuser"
            - name: MARIADB_PASSWORD
              value: "vdipw"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
